### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by parisio** [ericmann/WP-PowerShell#1]
Hi.  Tried installing a few times, but I get the following errors. What do you think? ie. what am I doing wrong? Running on Windows 7.  Also, as a side note, I recently changed my OS username to ParisIonescu (without the space) for better compatibility with unix style shells, but it doesn't look like PowerShell has picked that up... Not sure if that's relevant.

C:\Users\Paris Ionescu\Documents\WindowsPowerShell\Modules>@powershell
Windows PowerShell
Copyright (C) 2012 Microsoft Corporation. All rights reserved.

PS C:\Users\Paris Ionescu\Documents\WindowsPowerShell\Modules> Import-Module WP-PowerShell

PS C:\Users> cd /
PS C:> cd xampp/htdocs
PS C:\xampp\htdocs> cd wp
PS C:\xampp\htdocs\wp> wp "home help"
Join-Path : Cannot find path 'C:\Users\Paris
Ionescu\Documents\WindowsPowerShell\Modules\WP-PowerShell\wp-cli\src\php' because it does not exist.
At C:\Users\Paris
Ionescu\Documents\WindowsPowerShell\Modules\WP-PowerShell\WP-PowerShell.psm1:67 char:13
-     $path = Join-Path $PSScriptRoot wp-cli\src\php -Resolve
-             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (C:\Users\Paris ...\wp-cli\src\php:String)
    [Join-Path], ItemNotFoundException
  - FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.JoinPathCommand

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\Paris
Ionescu\Documents\WindowsPowerShell\Modules\WP-PowerShell\WP-PowerShell.psm1:39 char:22
-     $cli = Join-Path $scriptPath \wp-cli\wp-cli-boot.php
-                      ~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationEx
    ception
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.P
    owerShell.Commands.JoinPathCommand

Could not open input file: home

**Comment by parisio** [comment]
Anybody?

**Comment by parisio** [comment]
Looks like I didn't have PHP installed properly on Windows back then but as a novice didn't understand that xampp's php did not apply to the general command line environment. Lesson learned, but in the mean time moved over to Vagrant as it suits my current wordpress command-line needs and wp-powershell does not appear to have much activity at the moment. Appreciate it nonetheless.

**Comment by ericmann** [comment]
Sorry, WP PowerShell is effectively unsupported at this point. It was a polyfill in use before we had better tools like VVV, and now that it's available I just keep this project here in case anyone wants historical references.
